apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  namespace: default
  labels:
    app: sparta-app
spec:
  selector:
    app: sparta-app
  ports:
    - protocol: TCP
      port: 80            # This is the port your clients will use.
      targetPort: 3000   # This is the app’s port within the cluster.
  type: LoadBalancer

